import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 20,
        marginBottom: 30,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    headerTitleContainer: {
        flex: 1,
        marginLeft: 20,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#000',
    },
    headerRight: {
        alignItems: 'flex-end',
    },
    totalAmount: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#21C063',
    },
    gstText: {
        fontSize: 12,
        color: '#888',
        marginTop: 4,
    },
    content: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    tabContainer: {
        flexDirection: 'row',
        height: 56,
        marginBottom: 30,
    },
    tabButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 16,
    },
    activeTab: {
        backgroundColor: '#21C063',
        shadowColor: '#21C063',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    inactiveTab: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    activeTabText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    inactiveTabText: {
        color: '#000000',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    inputSection: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F9',
        height: 56,
        borderRadius: 16,
        paddingHorizontal: 16,
        borderWidth: 0,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#000',
    },
    cardIcons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    halfInput: {
        width: '47%',
    },
    infoText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
        marginTop: 10,
        marginBottom: 40,
        paddingHorizontal: 20,
        lineHeight: 18,
    },
    payButton: {
        backgroundColor: '#21C063',
        height: 56,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#21C063',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
    },
    payButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 8,
    },
});
